name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
# This is all from
# https://medium.com/intelligentmachines/github-actions-end-to-end-ci-cd-pipeline-for-django-5d48d6f00abf
  test-and-generate-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest
      - name: Generate coverage and check if Coverage.svg has changed
        id: generate
        run: |
          output=$((python generate_coverage.py) >&1) 
          if [[ "${output##* }" == "UPDATED" ]]; then
            echo "::set-output name=Coverage_changed::true"
          else
            echo "OUTPUT: ${output##* }"
          fi
      - name: Commit Coverage.svg if the file has changed
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'BollaBerg@users.noreply.github.com'
          git add Coverage.svg
          git commit -m "AUTOMATED: Update Coverage.svg"
          git push
        if: steps.generate.outputs.Coverage_changed == 'true'