name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
# This is all from
# https://medium.com/intelligentmachines/github-actions-end-to-end-ci-cd-pipeline-for-django-5d48d6f00abf
  test-and-generate-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python generate_coverage.py
      - name: Generate list of changed files
        run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV
      - name: Check if Coverage.svg has changed
        run: |
          for file in $CHANGED_FILES; do
            echo ${file}