name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
# This is all from
# https://medium.com/intelligentmachines/github-actions-end-to-end-ci-cd-pipeline-for-django-5d48d6f00abf
  test-and-generate-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python generate_coverage.py
      - name: Update Coverage.svg
        run: |
          git add Coverage.svg
          git commit -m "Updage Coverage.svg"
          git push